version: "3.9"

services:
  fastapi-app:
    build: .
    container_name: aimana_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # isso mantém o código sincronizado com o container
    restart: unless-stopped
